# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  pause-after-unit-refresh:
    description: |
      Wait for manual confirmation to resume refresh after these units refresh

      Allowed values: "all", "first", "none"
    type: string
    default: first
  tls-peer-private-key:
    type: secret
    description: |
      A Juju secret URI of a secret containing the private key for peer-to-peer TLS certificates.

  tls-client-private-key:
    type: secret
    description: |
      A Juju secret URI of a secret containing the private key for client-to-server TLS certificates.
