# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

[tool.poetry]
# Charm is not packed as a standard Python package; this information is not used
name = "charm"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
attrs = "^22.2.0"
cffi = "^1.15.1"
cosl = "^0.0.5"
importlib-resources = "^5.10.2"
tenacity = "^8.1.0"
pymongo = "^4.3.3"
ops = "^2.4.1"
cryptography = "^38.0.4"
pure-sasl = "^0.6.2"
pycparser = "^2.2"
pkgutil-resolve-name = "^1.3.10"
pydantic = "^1.10.12"
pyrsistent = "^0.19.3"
pyyaml = "^6.0.1"
zipp = "^3.11.0"
pyopenssl = "^22.1.0"
typing-extensions = "^4.5.0"
parameterized = "^0.9.0"
jsonschema = "^4.20.0"

[tool.poetry.group.charm-libs.dependencies]
# data_platform_libs/v0/data_interfaces.py
ops = ">=2.0.0"
# tls_certificates_interface/v1/tls_certificates.py
cryptography = "*"
jsonschema = "*"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
black = "^23.11.0"
ruff = "^0.1.6"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
black = "^23.11.0"
ruff = "^0.1.6"
codespell = "^2.2.6"
pyright = "^1.1.337"

[tool.poetry.group.unit.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"
jsonschema = "^4.20.0"
pytest-mock = "^3.12.0"

[tool.poetry.group.integration.dependencies]
pytest = "^7.4.3"
juju = "^3.2.0"
pytest-operator = "^0.28.0"
coverage = "^7.3.2"
protobuf = "3.20"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
