# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
env_list = lint

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
set_env =
    PYTHONPATH = {[vars]src_path}:{tox_root}/lib
    PY_COLORS = 1
allowlist_externals =
    sh
    poetry

[testenv:format]
description = Apply coding style standards to code
commands_pre =
    poetry install --only format
commands =
    poetry lock
    poetry run ruff format {[vars]all_path}
    poetry run ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
commands_pre =
    poetry install --only lint
commands =
    poetry check --lock
    codespell {[vars]all_path} --skip .git --skip .tox --skip build --skip venv --skip .mypy_cache --skip {tox_root}/src/grafana_dashboards --skip {tox_root}/tests/integration/*/lib/*
    poetry run ruff check {[vars]all_path}

[testenv:integration]
description = Run integration tests
pass_env =
    CI
    GITHUB_OUTPUT
commands_pre =
    sh -c 'if [ "$CI" = true ]; then sudo snap install charmcraft --classic; fi'
    sh -c 'if [ "$CI" = true ]; then sudo apt update && sudo apt install -y build-essential python3-dev libldap-dev libsasl2-dev; fi'
    poetry install --only integration
commands =
    poetry run pytest -v --tb native --log-cli-level=INFO -s {posargs}

[testenv:terraform-lint]
description = Format and validate Terraform modules
allowlist_externals =
    {[testenv]allowlist_externals}
    terraform
commands =
    terraform -chdir="{tox_root}/terraform/" init
    terraform -chdir="{tox_root}/terraform/" fmt -check
    terraform -chdir="{tox_root}/terraform/" validate
    terraform -chdir="{tox_root}/terraform/tests" init
    terraform -chdir="{tox_root}/terraform/tests" fmt -check
    terraform -chdir="{tox_root}/terraform/tests" validate

[testenv:terraform-test]
description = Run Terraform tests. Usage: tox -e terraform-test -- <model_uuid>
commands =
    sh -c 'if [ -z "$1" ]; then echo "Usage: tox -e terraform-test -- <model_uuid>"; exit 2; fi; cd "{tox_root}/terraform/tests" && terraform init && terraform apply -var "model_uuid=$1" -auto-approve' terraform-test {posargs}
