# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v21.0.0


  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.4.0
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }} # FIXME: current token will expire in 2023-07-04
          github-token: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

  build:
    strategy:
      fail-fast: false
      matrix:
        path:
          - .
          - tests/integration/application
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v21.0.0
    with:
      path-to-charm-directory: ${{ matrix.path }}
      cache: true

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        juju:
          # This runs on all runs
          - agent: 3.5.3 # renovate: juju-agent-pin-minor
            allure_report: true
          # This runs only on scheduled runs, DPW 21 specifics (scheduled + 3.6/X)
          - snap_channel: 3.6/beta
            allure_report: false
    name: Integration test charm | ${{ matrix.juju.agent || matrix.juju.snap_channel }}
    needs:
      - lint
      - unit-test
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@v21.0.0
    with:
      artifact-prefix: packed-charm-cache-true
      cloud: lxd
      juju-agent-version: ${{ matrix.juju.agent }}
      juju-snap-channel: ${{ matrix.juju.snap_channel }}
      _beta_allure_report: ${{ matrix.juju.allure_report }}
    permissions:
      contents: write
