name: Release to 6/edge

on:
  push:

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@artifact-v4